# Generated by Django 5.0.2 on 2024-03-03 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_client_inventory_orders_productdetail_food_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='Species_Name',
            new_name='species_Name',
        ),
    ]
